#!/bin/bash
##################################################################################
#
# THIS SH FILE WAS GENERATED BY THE scriptgenmax.php PHP SCRIPT
# THIS SCRIPT IS INTENDED TO BE A GENERATED SH FILE FOR RUNNING BATCH COMMANDS
#
##################################################################################
clia=/usr/local/bin/clia
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=AbstractInstance group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=AbstractInstance crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=AbstractInstance group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=AbstractInstance crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=AlertDataView group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=AlertDataView crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=AlertDataView group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=AlertDataView crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Batch group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Batch crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Batch group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Batch crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Calendar group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Calendar crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Calendar group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Calendar crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=CalendarEvent group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=CalendarEvent crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=CalendarEvent group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=CalendarEvent crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=CalendarEventRecurring group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=CalendarEventRecurring crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=CalendarEventRecurring group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=CalendarEventRecurring crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Collection group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Collection crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Collection group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Collection crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=CollectionMembers group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=CollectionMembers crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=CollectionMembers group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=CollectionMembers crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Condition group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Condition crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Condition group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Condition crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Correspondence group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Correspondence crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Correspondence group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Correspondence crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Counter group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Counter crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Counter group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Counter crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Currency group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Currency crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Currency group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Currency crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataSource group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataSource crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataSource group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataSource crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataTableDataView group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataTableDataView crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataTableDataView group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataTableDataView crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataView group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataView crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataView group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataView crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataViewField group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataViewField crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataViewField group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataViewField crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataViewMathColumn group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataViewMathColumn crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataViewMathColumn group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataViewMathColumn crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataViewParameter group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataViewParameter crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataViewParameter group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataViewParameter crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataViewParameterBoolean group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataViewParameterBoolean crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataViewParameterBoolean group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataViewParameterBoolean crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataViewParameterDate group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataViewParameterDate crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataViewParameterDate group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataViewParameterDate crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataViewParameterDateTime group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataViewParameterDateTime crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataViewParameterDateTime group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataViewParameterDateTime crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataViewParameterMultipleSelect group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataViewParameterMultipleSelect crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataViewParameterMultipleSelect group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataViewParameterMultipleSelect crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DataViewParameterSelect group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DataViewParameterSelect crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DataViewParameterSelect group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DataViewParameterSelect crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DateRangeValue group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DateRangeValue crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DateRangeValue group='Rates Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DateRangeValue crud=Create,Read,Update
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DetailDataView group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DetailDataView crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DetailDataView group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DetailDataView crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DetailDataViewField group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DetailDataViewField crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DetailDataViewField group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DetailDataViewField crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DocumentCategory group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DocumentCategory crud=Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DocumentCategory group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DocumentCategory crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=DocumentTemplate group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=DocumentTemplate crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=DocumentTemplate group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=DocumentTemplate crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Doughnut group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Doughnut crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Doughnut group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Doughnut crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Esign group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Esign crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Esign group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Esign crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=EsignEntry group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=EsignEntry crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=EsignEntry group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=EsignEntry crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=EventDataView group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=EventDataView crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=EventDataView group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=EventDataView crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=EventFrequency group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=EventFrequency crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=EventFrequency group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=EventFrequency crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ExpressionEvaluator group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ExpressionEvaluator crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ExpressionEvaluator group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ExpressionEvaluator crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Group group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Group crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Group group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Group crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=GroupPermissionTemplate group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=GroupPermissionTemplate crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=GroupPermissionTemplate group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=GroupPermissionTemplate crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Group_Role_Link group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Group_Role_Link crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Group_Role_Link group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Group_Role_Link crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Image group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Image crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Image group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Image crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ImageDefinition group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ImageDefinition crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ImageDefinition group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ImageDefinition crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ImageGroup group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ImageGroup crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ImageGroup group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ImageGroup crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ImageItemOcr group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ImageItemOcr crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ImageItemOcr group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ImageItemOcr crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ItemListDataView group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ItemListDataView crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ItemListDataView group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ItemListDataView crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ItemListMore group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ItemListMore crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ItemListMore group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ItemListMore crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Layout group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Layout crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Layout group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Layout crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=LineChart group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=LineChart crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=LineChart group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=LineChart crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=LoaderRateDateRangeValue group='Justin Ward'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=LoaderRateDateRangeValue crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=LoaderRateDateRangeValue group='Justin Ward'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=LoaderRateDateRangeValue crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=MDateTime group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=MDateTime crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=MDateTime group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=MDateTime crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=MenuItem group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=MenuItem crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=MenuItem group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=MenuItem crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Message group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Message crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Message group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Message crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=MessagePermissionUser group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=MessagePermissionUser crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=MessagePermissionUser group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=MessagePermissionUser crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=MFile group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=MFile crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=MFile group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=MFile crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectActionLog group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectActionLog crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectActionLog group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectActionLog crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectAttachment group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectAttachment crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectAttachment group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectAttachment crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectCrudAction group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectCrudAction crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectCrudAction group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectCrudAction crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectCrudActionAlarm group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectCrudActionAlarm crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectCrudActionAlarm group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectCrudActionAlarm crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectCrudActionAlert group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectCrudActionAlert crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectCrudActionAlert group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectCrudActionAlert crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectCrudActionError group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectCrudActionError crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectCrudActionError group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectCrudActionError crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectCrudActionProcess group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectCrudActionProcess crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectCrudActionProcess group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectCrudActionProcess crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectDataReference group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectDataReference crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectDataReference group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectDataReference crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldBoolean group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldBoolean crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldBoolean group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldBoolean crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldCalculated group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldCalculated crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldCalculated group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldCalculated crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldDate group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldDate crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldDate group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldDate crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldDateTime group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldDateTime crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldDateTime group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldDateTime crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldEnum group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldEnum crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldEnum group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldEnum crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldForeignKey group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldForeignKey crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldForeignKey group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldForeignKey crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldForeignKeyFile group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldForeignKeyFile crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldForeignKeyFile group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldForeignKeyFile crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldLargeText group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldLargeText crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldLargeText group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldLargeText crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldMonetary group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldMonetary crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldMonetary group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldMonetary crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldNumber group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldNumber crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldNumber group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldNumber crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldSet group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldSet crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldSet group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldSet crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectFieldText group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectFieldText crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectFieldText group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectFieldText crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectInstanceLog group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectInstanceLog crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectInstanceLog group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectInstanceLog crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectLog group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectLog crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectLog group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectLog crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectNote group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectNote crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectNote group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectNote crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectRegistry group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectRegistry crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectRegistry group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectRegistry crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectRegistryDescriptiveField group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectRegistryDescriptiveField crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectRegistryDescriptiveField group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectRegistryDescriptiveField crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ObjectRegistryField group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ObjectRegistryField crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ObjectRegistryField group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ObjectRegistryField crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=OcrImageNote group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=OcrImageNote crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=OcrImageNote group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=OcrImageNote crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Order group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Order crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Order group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Order crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=PaymentLog group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=PaymentLog crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=PaymentLog group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=PaymentLog crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=PermissionRole group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=PermissionRole crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=PermissionRole group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=PermissionRole crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=PermissionUser group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=PermissionUser crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=PermissionUser group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=PermissionUser crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=PersistedResultSet group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=PersistedResultSet crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=PersistedResultSet group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=PersistedResultSet crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Person group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Person crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Person group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Person crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Preference group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Preference crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Preference group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Preference crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=PreferenceDescription group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=PreferenceDescription crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=PreferenceDescription group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=PreferenceDescription crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Process group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Process crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Process group='ProcessRunners'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Process crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ProcessStep group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ProcessStep crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ProcessStep group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ProcessStep crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ProcessSubscription group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ProcessSubscription crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ProcessSubscription group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ProcessSubscription crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ProcessTracker group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ProcessTracker crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ProcessTracker group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ProcessTracker crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Process_role_link group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Process_role_link crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Process_role_link group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Process_role_link crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Queue group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Queue crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Queue group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Queue crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=QueueEntry group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=QueueEntry crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=QueueEntry group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=QueueEntry crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=QueueEntryClia group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=QueueEntryClia crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=QueueEntryClia group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=QueueEntryClia crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=QueueEntryEmail group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=QueueEntryEmail crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=QueueEntryEmail group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=QueueEntryEmail crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=QueueEntryImportedTrip group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=QueueEntryImportedTrip crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=QueueEntryImportedTrip group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=QueueEntryImportedTrip crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=QueueEntryOcr group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=QueueEntryOcr crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=QueueEntryOcr group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=QueueEntryOcr crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=QueueEntryOfflineTrip group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=QueueEntryOfflineTrip crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=QueueEntryOfflineTrip group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=QueueEntryOfflineTrip crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=QueueEntryProcess group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=QueueEntryProcess crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=QueueEntryProcess group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=QueueEntryProcess crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=QueueEntrySearch group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=QueueEntrySearch crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=QueueEntrySearch group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=QueueEntrySearch crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=QueueEntrySMS group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=QueueEntrySMS crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=QueueEntrySMS group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=QueueEntrySMS crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=QueueEntrySyspro group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=QueueEntrySyspro crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=QueueEntrySyspro group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=QueueEntrySyspro crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=RateDateRangeValue group='Justin Ward'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=RateDateRangeValue crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=RateDateRangeValue group='Justin Ward'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=RateDateRangeValue crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ReleaseLog group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ReleaseLog crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ReleaseLog group='ProcessRunners'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ReleaseLog crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ReleaseNote group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ReleaseNote crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ReleaseNote group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ReleaseNote crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Report group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Report crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Report group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Report crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ReportGroup group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ReportGroup crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ReportGroup group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ReportGroup crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=ResultSet group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=ResultSet crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=ResultSet group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=ResultSet crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Sequence group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Sequence crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Sequence group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Sequence crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Setting group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Setting crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Setting group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Setting crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=StartupProcess group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=StartupProcess crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=StartupProcess group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=StartupProcess crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=StartupProcessUser group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=StartupProcessUser crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=StartupProcessUser group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=StartupProcessUser crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=stat group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=stat crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=stat group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=stat crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=StyleSetting group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=StyleSetting crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=StyleSetting group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=StyleSetting crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=SupportIssue group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=SupportIssue crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=SupportIssue group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=SupportIssue crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=Tab group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=Tab crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=Tab group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=Tab crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=TabDataView group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=TabDataView crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=TabDataView group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=TabDataView crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=TenantConfig group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=TenantConfig crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=TenantConfig group='Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=TenantConfig crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_AccountManager group='Customers Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_AccountManager crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_AccountManager group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_AccountManager crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_AccountStatus group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_AccountStatus crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_AccountStatus group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_AccountStatus crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Assistant group='Team Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Assistant crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Assistant group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Assistant crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_BusinessUnit group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_BusinessUnit crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_BusinessUnit group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_BusinessUnit crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Cargo group='TripManagers'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Cargo crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Cargo group='Public'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Cargo crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_CargoBatchUpdate group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_CargoBatchUpdate crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_CargoBatchUpdate group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_CargoBatchUpdate crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_ChepDepot group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_ChepDepot crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_ChepDepot group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_ChepDepot crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_City group='Locations'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_City crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_City group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_City crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_ContactType group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_ContactType crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_ContactType group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_ContactType crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Continent group='Locations'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Continent crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Continent group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Continent crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Country group='Locations'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Country crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Country group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Country crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_CurrencyExchangeRate group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_CurrencyExchangeRate crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_CurrencyExchangeRate group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_CurrencyExchangeRate crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Customer group='Customers Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Customer crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Customer group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Customer crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_CustomerAdminDetails group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_CustomerAdminDetails crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_CustomerAdminDetails group='Customers Admin'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_CustomerAdminDetails crud=Create,Read,Update
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_CustomerBusinessUnit_link group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_CustomerBusinessUnit_link crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_CustomerBusinessUnit_link group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_CustomerBusinessUnit_link crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_CustomerContacts group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_CustomerContacts crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_CustomerContacts group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_CustomerContacts crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_CustomerCustomerType group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_CustomerCustomerType crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_CustomerCustomerType group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_CustomerCustomerType crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_CustomerLocations group='Locations'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_CustomerLocations crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_CustomerLocations group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_CustomerLocations crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_CustomerLocationsBusinessUnit_link group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_CustomerLocationsBusinessUnit_link crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_CustomerLocationsBusinessUnit_link group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_CustomerLocationsBusinessUnit_link crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_CustomerProcedures group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_CustomerProcedures crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_CustomerProcedures group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_CustomerProcedures crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_CustomerType group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_CustomerType crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_CustomerType group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_CustomerType crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Debrief group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Debrief crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Debrief group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Debrief crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_DebriefGrid group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_DebriefGrid crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_DebriefGrid group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_DebriefGrid crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_DebriefGridRow group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_DebriefGridRow crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_DebriefGridRow group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_DebriefGridRow crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_DebriefIncompleteDocumentationReason group='All Users'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_DebriefIncompleteDocumentationReason crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_DebriefIncompleteDocumentationReason group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_DebriefIncompleteDocumentationReason crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_DebriefTripExceptionLink group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_DebriefTripExceptionLink crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_DebriefTripExceptionLink group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_DebriefTripExceptionLink crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_DeletedTrip group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_DeletedTrip crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_DeletedTrip group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_DeletedTrip crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Depot group='Justin Ward'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Depot crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Depot group='Justin Ward'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Depot crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_DieselPrice group='Justin Ward'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_DieselPrice crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_DieselPrice group='Justin Ward'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_DieselPrice crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Driver group='Team Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Driver crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Driver group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Driver crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_DriverActivity group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_DriverActivity crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_DriverActivity group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_DriverActivity crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_DummyOrder group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_DummyOrder crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_DummyOrder group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_DummyOrder crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Envelope group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Envelope crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Envelope group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Envelope crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_EpodImageDefinitionsExclude group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_EpodImageDefinitionsExclude crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_EpodImageDefinitionsExclude group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_EpodImageDefinitionsExclude crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_FandVContract group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_FandVContract crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_FandVContract group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_FandVContract crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_FandVContractRoute_link group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_FandVContractRoute_link crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_FandVContractRoute_link group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_FandVContractRoute_link crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_FandVContractTruck_link group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_FandVContractTruck_link crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_FandVContractTruck_link group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_FandVContractTruck_link crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Fleet group='Fleet'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Fleet crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Fleet group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Fleet crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_FleetBudgetFactor group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_FleetBudgetFactor crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_FleetBudgetFactor group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_FleetBudgetFactor crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_FleetBudgetTotal group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_FleetBudgetTotal crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_FleetBudgetTotal group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_FleetBudgetTotal crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_FleetTruckLink group='Fleet'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_FleetTruckLink crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_FleetTruckLink group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_FleetTruckLink crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_FleetType group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_FleetType crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_FleetType group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_FleetType crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_FuelException group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_FuelException crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_FuelException group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_FuelException crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_FuelPrice group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_FuelPrice crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_FuelPrice group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_FuelPrice crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_FuelRoute group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_FuelRoute crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_FuelRoute group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_FuelRoute crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_HollowAdhoc group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_HollowAdhoc crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_HollowAdhoc group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_HollowAdhoc crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_ImportedTrip group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_ImportedTrip crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_ImportedTrip group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_ImportedTrip crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_IndustryClass group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_IndustryClass crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_IndustryClass group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_IndustryClass crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Loader group='Justin Ward'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Loader crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Loader group='Justin Ward'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Loader crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_LoaderRate group='Justin Ward'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_LoaderRate crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_LoaderRate group='Justin Ward'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_LoaderRate crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_LoaderRateAdjustment group='Justin Ward'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_LoaderRateAdjustment crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_LoaderRateAdjustment group='Justin Ward'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_LoaderRateAdjustment crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_LoadingCharges group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_LoadingCharges crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_LoadingCharges group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_LoadingCharges crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_LocalAllocation group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_LocalAllocation crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_LocalAllocation group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_LocalAllocation crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_LocalCharges group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_LocalCharges crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_LocalCharges group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_LocalCharges crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_LocalOrders group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_LocalOrders crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_LocalOrders group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_LocalOrders crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Location group='Locations'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Location crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Location group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Location crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_LocsTruck group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_LocsTruck crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_LocsTruck group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_LocsTruck crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Make group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Make crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Make group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Make crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_ManlineDepot group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_ManlineDepot crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_ManlineDepot group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_ManlineDepot crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_ManualPosition group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_ManualPosition crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_ManualPosition group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_ManualPosition crud=Create,Read,Update
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Mill group='Justin Ward'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Mill crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Mill group='Justin Ward'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Mill crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Model group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Model crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Model group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Model crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Notes group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Notes crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Notes group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Notes crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_OffloadingCustomers group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_OffloadingCustomers crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_OffloadingCustomers group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_OffloadingCustomers crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_OffloadingCustomersBusinessUnit_link group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_OffloadingCustomersBusinessUnit_link crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_OffloadingCustomersBusinessUnit_link group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_OffloadingCustomersBusinessUnit_link crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_PalletType group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_PalletType crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_PalletType group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_PalletType crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_PaymentMethod group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_PaymentMethod crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_PaymentMethod group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_PaymentMethod crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_PaymentTerms group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_PaymentTerms crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_PaymentTerms group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_PaymentTerms crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Plantation group='Justin Ward'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Plantation crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Plantation group='Justin Ward'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Plantation crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Point group='Locations'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Point crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Point group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Point crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Point_Point_Type group='Locations'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Point_Point_Type crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Point_Point_Type group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Point_Point_Type crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Point_Type group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Point_Type crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Point_Type group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Point_Type crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Position group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Position crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Position group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Position crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_PositionDestination group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_PositionDestination crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_PositionDestination group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_PositionDestination crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_PreferenceDescription group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_PreferenceDescription crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_PreferenceDescription group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_PreferenceDescription crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Process_Graph group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Process_Graph crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Process_Graph group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Process_Graph crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_ProductCategory group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_ProductCategory crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_ProductCategory group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_ProductCategory crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_ProductDetail group='Rates Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_ProductDetail crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_ProductDetail group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_ProductDetail crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_ProductType group='Rates Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_ProductType crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_ProductType group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_ProductType crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Proposal group='Proposal Approver'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Proposal crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Proposal group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Proposal crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Province group='Locations'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Province crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Province group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Province crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Quote group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Quote crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Quote group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Quote crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_QuoteRate group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_QuoteRate crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_QuoteRate group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_QuoteRate crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_RateAdjustment group='Rates Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_RateAdjustment crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_RateAdjustment group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_RateAdjustment crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Rates group='Rates Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Rates crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Rates group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Rates crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_RatesAdjustment group='Rates Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_RatesAdjustment crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_RatesAdjustment group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_RatesAdjustment crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_RateType group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_RateType crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_RateType group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_RateType crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Refuel group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Refuel crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Refuel group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Refuel crud=Create,Read,Update
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_RefuelOrderNumber group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_RefuelOrderNumber crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_RefuelOrderNumber group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_RefuelOrderNumber crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Route group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Route crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Route group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Route crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_RouteCache group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_RouteCache crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_RouteCache group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_RouteCache crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_RouteCacheSummary group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_RouteCacheSummary crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_RouteCacheSummary group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_RouteCacheSummary crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_RouteTollGate_link group='Justin Ward'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_RouteTollGate_link crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_RouteTollGate_link group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_RouteTollGate_link crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Subcontractor group='Customers Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Subcontractor crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Subcontractor group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Subcontractor crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_SubcontractorContact group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_SubcontractorContact crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_SubcontractorContact group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_SubcontractorContact crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_SubcontractorFleet_link group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_SubcontractorFleet_link crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_SubcontractorFleet_link group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_SubcontractorFleet_link crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_SubcontractorType group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_SubcontractorType crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_SubcontractorType group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_SubcontractorType crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Suburb group='Locations'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Suburb crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Suburb group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Suburb crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Timeframe group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Timeframe crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Timeframe group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Timeframe crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TimeframeFuelExceptionLink group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TimeframeFuelExceptionLink crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TimeframeFuelExceptionLink group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TimeframeFuelExceptionLink crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Toll group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Toll crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Toll group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Toll crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TollClass group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TollClass crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TollClass group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TollClass crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TollGate group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TollGate crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TollGate group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TollGate crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Trailer group='Fleet'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Trailer crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Trailer group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Trailer crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TrailerMake group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TrailerMake crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TrailerMake group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TrailerMake crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TrailerModel group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TrailerModel crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TrailerModel group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TrailerModel crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Trip group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Trip crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Trip group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Trip crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TripException group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TripException crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TripException group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TripException crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TripLeg group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TripLeg crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TripLeg group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TripLeg crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TripLegCargo group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TripLegCargo crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TripLegCargo group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TripLegCargo crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TripProject group='TripManagers'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TripProject crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TripProject group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TripProject crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Truck group='Fleet'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Truck crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Truck group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Truck crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TruckBudget group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TruckBudget crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TruckBudget group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TruckBudget crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_TruckDescription group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_TruckDescription crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_TruckDescription group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_TruckDescription crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_UnassignedCargo group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_UnassignedCargo crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_UnassignedCargo group='Manline'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_UnassignedCargo crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_Zone group='Rates Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_Zone crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_Zone group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_Zone crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=udo_ZoneCity_link group='Rates Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=udo_ZoneCity_link crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=udo_ZoneCity_link group='System'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=udo_ZoneCity_link crud=Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=UniqueConstraint group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=UniqueConstraint crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=UniqueConstraint group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=UniqueConstraint crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=UniqueConstraintField group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=UniqueConstraintField crud=Create,Read,Update
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=UniqueConstraintField group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=UniqueConstraintField crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=VersionControl group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=VersionControl crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=VersionControl group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=VersionControl crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=VersionControlItem group='System'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=VersionControlItem crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=VersionControlItem group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=VersionControlItem crud=Create,Read
$clia ObjectRegistry setObjectPrimaryOwnerGroup objectRegistry=View group='Admin'
$clia ObjectRegistry setObjectPrimaryOwnerCrud objectRegistry=View crud=Create,Read,Update,Delete
$clia ObjectRegistry setObjectGroupOwnerGroup objectRegistry=View group='All Users'
$clia ObjectRegistry setObjectGroupOwnerCrud objectRegistry=View crud=Read
