#!/bin/bash
##################################################################################
#
# THIS SH FILE WAS GENERATED BY THE scriptgenmax.php PHP SCRIPT
# THIS SCRIPT IS INTENDED TO BE A GENERATED SH FILE FOR RUNNING BATCH COMMANDS
#
##################################################################################
clia=/usr/local/bin/clia

$clia DataView setPermissionsForId dataViewId=616 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=617 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=618 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=619 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=620 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=621 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=622 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=623 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=624 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=625 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=626 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=627 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=628 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=629 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=630 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=631 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=632 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=633 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=634 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=635 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=636 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=637 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=638 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=639 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=640 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=641 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=642 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=643 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=644 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=645 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=646 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=647 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=648 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=649 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=650 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=651 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=652 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=653 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=654 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=655 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=656 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=657 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=658 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=659 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=660 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=661 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=662 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=663 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=664 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=665 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=666 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=667 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=668 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=669 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=670 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=671 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=672 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=673 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=674 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=675 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=676 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=677 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=678 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=679 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=680 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=681 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=682 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=683 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=684 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=685 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=686 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=687 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=688 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=689 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=690 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=691 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=692 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=693 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=694 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=695 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=696 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=697 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=698 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=699 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=700 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=701 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=702 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=703 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=704 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=705 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=706 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=707 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=708 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=709 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=710 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Reports' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=711 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=712 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=713 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=714 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=715 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=716 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=717 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=718 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=719 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=722 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read,Update
$clia DataView setPermissionsForId dataViewId=723 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read,Update
$clia DataView setPermissionsForId dataViewId=724 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=725 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=726 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=727 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=728 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=729 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=730 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=731 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=732 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=733 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=734 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=735 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=736 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Create,Read
$clia DataView setPermissionsForId dataViewId=737 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=738 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=739 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=742 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Reports' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=743 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read,Update
$clia DataView setPermissionsForId dataViewId=744 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=745 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Create,Read,Update
$clia DataView setPermissionsForId dataViewId=746 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=747 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=748 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=749 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=750 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=751 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=752 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=753 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=754 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=755 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Refuel' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=756 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=758 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=759 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=760 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=761 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=762 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=763 primaryOwner='All Users' primaryOwnerCrud=Read groupOwner='System' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=764 primaryOwner='All Users' primaryOwnerCrud=Read groupOwner='System' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=765 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=766 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=767 primaryOwner='All Users' primaryOwnerCrud=Read groupOwner='System' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=768 primaryOwner='All Users' primaryOwnerCrud=Read groupOwner='System' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=769 primaryOwner='All Users' primaryOwnerCrud=Read groupOwner='System' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=770 primaryOwner='All Users' primaryOwnerCrud=Read groupOwner='System' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=771 primaryOwner='All Users' primaryOwnerCrud=Read groupOwner='System' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=772 primaryOwner='All Users' primaryOwnerCrud=Read groupOwner='System' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=773 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=774 primaryOwner='System' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Create,Read,Update
$clia DataView setPermissionsForId dataViewId=776 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=777 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=778 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=779 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=780 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=782 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=785 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=786 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=787 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Reports' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=789 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=791 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=792 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=793 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Create,Read,Update
$clia DataView setPermissionsForId dataViewId=795 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=796 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=797 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=798 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=799 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=800 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=801 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=802 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=803 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Reports' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=804 primaryOwner='System' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='System' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=805 primaryOwner='System' primaryOwnerCrud=Read,Update,Delete groupOwner='System' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=806 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=807 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=808 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=809 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=810 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=811 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=812 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=813 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=814 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=815 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=816 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=818 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=819 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=820 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=821 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=822 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=823 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=824 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=825 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=826 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=827 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=833 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=834 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=835 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=836 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=838 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=839 primaryOwner='Cheryl James' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Reports' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=840 primaryOwner='Admin' primaryOwnerCrud=Read,Update groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=841 primaryOwner='Admin' primaryOwnerCrud=Read,Update groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=842 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Create,Read,Update
$clia DataView setPermissionsForId dataViewId=845 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=846 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=847 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=849 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=850 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=852 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=853 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=854 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=855 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Meryle Moodley' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=856 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=858 primaryOwner='Manline' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=859 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Sherlocks Report Viewer' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=860 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=861 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=863 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=864 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=866 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=867 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=868 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=869 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=870 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manager' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=873 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Reports' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=874 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Finance Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=875 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Cheryl James' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=876 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=877 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=880 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=881 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=882 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=883 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=884 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=885 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=886 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=887 primaryOwner='Feighen Oosterbroek' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Feighen Oosterbroek' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=888 primaryOwner='Reports' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Feighen Oosterbroek' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=889 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=890 primaryOwner='Reports' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Feighen Oosterbroek' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=891 primaryOwner='Manager' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Feighen Oosterbroek' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=892 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=893 primaryOwner='Reports' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Clinton Wright' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=894 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=895 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=896 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update groupOwner='Customers Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=897 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=898 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=899 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=900 primaryOwner='Feighen Oosterbroek' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=901 primaryOwner='Marcus Ganesh' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=903 primaryOwner='Clinton Wright' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Reports' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=904 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=905 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=906 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=907 primaryOwner='Admin' primaryOwnerCrud=Read,Update groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=908 primaryOwner='Admin' primaryOwnerCrud=Read,Update groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=909 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=910 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=911 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=912 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=913 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=914 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=915 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read,Update
$clia DataView setPermissionsForId dataViewId=916 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=917 primaryOwner='System' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Create,Read,Update
$clia DataView setPermissionsForId dataViewId=918 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=919 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Refuel' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=920 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=921 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=922 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=923 primaryOwner='All Users' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=924 primaryOwner='All Users' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=925 primaryOwner='All Users' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=926 primaryOwner='Feighen Oosterbroek' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=928 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=929 primaryOwner='Feighen Oosterbroek' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=930 primaryOwner='Feighen Oosterbroek' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=931 primaryOwner='System' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=932 primaryOwner='System' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=933 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=934 primaryOwner='Admin' primaryOwnerCrud=Read,Update groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=935 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=936 primaryOwner='Feighen Oosterbroek' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=937 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=938 primaryOwner='Justin Ward' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=939 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=940 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=941 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=942 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=943 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Reports' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=944 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=945 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=946 primaryOwner='Justin Ward' primaryOwnerCrud=Read,Update,Delete groupOwner='Justin Ward' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=947 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=948 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=949 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=950 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=951 primaryOwner='Clinton Wright' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=952 primaryOwner='Feighen Oosterbroek' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=954 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=955 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=956 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Refuel' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=957 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=958 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=962 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=963 primaryOwner='System' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=964 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=965 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=966 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=967 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=968 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=969 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=970 primaryOwner='System' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=973 primaryOwner='System' primaryOwnerCrud=Create,Read,Update groupOwner='Admin' groupOwnerCrud=Create,Read,Update
$clia DataView setPermissionsForId dataViewId=974 primaryOwner='Feighen Oosterbroek' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=975 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=976 primaryOwner='System' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=977 primaryOwner='System' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=978 primaryOwner='System' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=979 primaryOwner='System' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=980 primaryOwner='System' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Create,Read,Update
$clia DataView setPermissionsForId dataViewId=981 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Create,Read,Update
$clia DataView setPermissionsForId dataViewId=982 primaryOwner='Admin' primaryOwnerCrud=Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Create,Read,Update
$clia DataView setPermissionsForId dataViewId=983 primaryOwner='System' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=984 primaryOwner='System' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Admin' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=985 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=986 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='Manline' groupOwnerCrud=Read
$clia DataView setPermissionsForId dataViewId=987 primaryOwner='Admin' primaryOwnerCrud=Create,Read,Update,Delete groupOwner='All Users' groupOwnerCrud=Read