#!/bin/bash
##################################################################################
#
# THIS SH FILE WAS GENERATED BY THE scriptgenmax.php PHP SCRIPT
# THIS SCRIPT IS INTENDED TO BE A GENERATED SH FILE FOR RUNNING BATCH COMMANDS
#
##################################################################################
clia=/usr/local/bin/clia
$clia ObjectRegistry assignPermissions object=udo_Loader 'id=1' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Loader 'id=2' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Loader 'id=3' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Loader 'id=4' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Loader 'id=5' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Loader 'id=6' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Loader 'id=7' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Loader 'id=8' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Loader 'id=9' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Loader 'id=10' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
