#!/bin/bash
##################################################################################
#
# THIS SH FILE WAS GENERATED BY THE scriptgenmax.php PHP SCRIPT
# THIS SCRIPT IS INTENDED TO BE A GENERATED SH FILE FOR RUNNING BATCH COMMANDS
#
##################################################################################
clia=/usr/local/bin/clia


