#!/bin/bash
##################################################################################
#
# THIS SH FILE WAS GENERATED BY THE scriptgenmax.php PHP SCRIPT
# THIS SCRIPT IS INTENDED TO BE A GENERATED SH FILE FOR RUNNING BATCH COMMANDS
#
##################################################################################
clia=/usr/local/bin/clia
$clia ObjectRegistry assignPermissions object=udo_Make 'id=4' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=5' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=6' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=7' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=8' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=9' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=10' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=11' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=12' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=13' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=14' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=15' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=16' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=17' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=18' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=19' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=20' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=21' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=22' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=23' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=24' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=25' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=26' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=27' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=28' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=29' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=30' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=31' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=32' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=33' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=34' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
$clia ObjectRegistry assignPermissions object=udo_Make 'id=35' primaryOwner='Team Admin' primaryOwnerCrud='Create,Read,Update,Delete' groupOwnerCrud='Read' groupOwner='All Users'
